[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fwengine"
version = "1.0.0"
description = "Engine de Automatización y Gobernanza de Datos"
authors = [{name = "DataWay"}]

[project.scripts]
# Esto conecta el comando 'fwengine' con la función 'main' dentro de 'FWengine.py'
fwengine = "FWengine:main"